version: '3.8'

services:
  web:
    build: .
    image: arborhub
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DEBUG=1
      - DATABASE_NAME_NEW=newdb
      - DATABASE_USER_NEW=postgres
      - DATABASE_PASSWORD_NEW=arborco87
      - DATABASE_HOST_NEW=postgres  # Use the service name for the database host
      - DATABASE_PORT_NEW=5432
    depends_on:
      - solr
      - postgres
    command: >
      # sh -c "python manage.py runserver 0.0.0.0:8000"

  solr:
    image: solr:latest
    ports:
      - "8986:8983"
    volumes:
      - /mnt/c/solr-9.7.0/core_arbor:/opt/solr/server/solr/mycores/core_arbor  # Updated to match your CMD
    command: solr-foreground

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=newdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=arborco87
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  solr_data:
  postgres_data:

