version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - solr
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  
  solr:
    image: solr:latest
    ports:
      - "8984:8983"
    volumes:
      - solr_data:/var/solr
    command: solr-foreground

volumes:
  solr_data:
