# Generated by Django 5.1 on 2024-08-30 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arborist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(max_length=30)),
                ('services_type', models.CharField(max_length=30)),
                ('reviews', models.CharField(max_length=200)),
                ('years_experience', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['business', 'location', 'services_type', 'reviews', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip_code', models.PositiveIntegerField()),
                ('bio', models.CharField(db_default='', max_length=100)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name', 'street_address', 'city', 'state', 'zip_code', 'bio', 'profile_pic'],
            },
        ),
    ]
