# Generated by Django 5.1 on 2024-09-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
