# Generated by Django 5.1 on 2024-09-01 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeowner',
            options={},
        ),
        migrations.CreateModel(
            name='ArboristReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_star', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('two_stars', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('three_stars', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('four_stars', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('five_stars', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('review_by_homeowner', models.CharField(max_length=300)),
                ('arborist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arborfindr.arborist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arborfindr.homeowner')),
            ],
        ),
    ]
