# Generated by Django 4.2.16 on 2024-10-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arboristcompany',
            name='company_city',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='arboristcompany',
            name='company_price',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='arboristcompany',
            name='company_state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='arboristcompany',
            name='experience',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='arboristcompany',
            name='company_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='pesticide_applications',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='soil_management',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='tree_biology',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='tree_planting',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='tree_protection',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='tree_pruning',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='tree_removal',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='servicestype',
            name='tree_risk_management',
            field=models.CharField(max_length=80),
        ),
    ]
