# Generated by Django 4.2.16 on 2024-11-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arboristreview',
            name='arborist_company',
        ),
    ]
