# Generated by Django 5.1 on 2024-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arboristcompany',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('company', 'Company')], max_length=15),
        ),
    ]
