# Generated by Django 4.2.14 on 2024-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0002_homeowner_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeowner',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
