# Generated by Django 5.1 on 2024-09-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arborist',
            name='price',
            field=models.IntegerField(null='True'),
        ),
    ]
