# Generated by Django 4.2.16 on 2024-11-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0002_remove_arboristreview_arborist_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='arboristreview',
            name='arborist_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arborfindr.arboristcompany'),
        ),
    ]
