# Generated by Django 5.1 on 2024-09-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0002_alter_homeowner_options_arboristreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arborist',
            options={'ordering': ['business', 'services_type', 'reviews', 'price']},
        ),
        migrations.RemoveField(
            model_name='arborist',
            name='location',
        ),
    ]
