# Generated by Django 4.2.16 on 2024-12-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0003_arboristreview_arborist_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='arboristreview',
            table='arborfindr_arboristreview',
        ),
    ]
