# Generated by Django 5.1 on 2024-09-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0003_arboristcompany_user_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arboristcompany',
            name='company_size',
        ),
        migrations.AddField(
            model_name='arboristcompany',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='company_logo'),
        ),
    ]
