# Generated by Django 4.2.14 on 2024-08-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0003_alter_homeowner_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeowner',
            name='price',
        ),
    ]
