# Generated by Django 5.1 on 2024-09-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0003_alter_arborist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arboristreview',
            name='five_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='arboristreview',
            name='four_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='arboristreview',
            name='one_star',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='arboristreview',
            name='three_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='arboristreview',
            name='two_stars',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
