# Generated by Django 5.1 on 2024-09-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0003_alter_arborist_options_remove_arborist_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arborist',
            options={'ordering': ['company', 'services_type', 'reviews', 'arborist_city', 'arborist_state', 'years_experience', 'price']},
        ),
        migrations.RemoveField(
            model_name='arborist',
            name='business',
        ),
        migrations.AddField(
            model_name='arborist',
            name='arborist_city',
            field=models.CharField(default='unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arborist',
            name='arborist_state',
            field=models.CharField(default='unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arborist',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
