# Generated by Django 5.1 on 2024-09-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0004_alter_arboristreview_five_stars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arborist',
            options={'ordering': ['arborist_city', 'arborist_state', 'years_experience', 'price']},
        ),
        migrations.RemoveField(
            model_name='arborist',
            name='company',
        ),
        migrations.RemoveField(
            model_name='arborist',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='arborist',
            name='services_type',
        ),
    ]
