# Generated by Django 4.2.14 on 2024-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0004_remove_homeowner_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arborist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('services_type', models.CharField(max_length=30)),
                ('reviews', models.CharField(max_length=200)),
                ('years_experience', models.CharField(max_length=30)),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
