# Generated by Django 5.1 on 2024-09-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0004_alter_arborist_options_remove_arborist_business_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_pruning', models.CharField(max_length=30)),
                ('tree_removal', models.CharField(max_length=30)),
                ('tree_planting', models.CharField(max_length=30)),
                ('pesticide_applications', models.CharField(max_length=30)),
                ('soil_management', models.CharField(max_length=30)),
                ('tree_protection', models.CharField(max_length=30)),
                ('tree_risk_management', models.CharField(max_length=30)),
                ('tree_biology', models.CharField(max_length=30)),
                ('arborist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arborfindr.arborist')),
            ],
        ),
    ]
