# Generated by Django 4.2.14 on 2024-08-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0005_arborist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arborist',
            name='business_name',
        ),
        migrations.AlterField(
            model_name='arborist',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='homeowner',
            name='zip_code',
            field=models.PositiveIntegerField(),
        ),
    ]
