# Generated by Django 4.2.14 on 2024-08-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0006_remove_arborist_business_name_alter_arborist_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arborist',
            name='business',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
