# Generated by Django 5.1 on 2024-08-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0007_arborist_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeownerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(upload_to='profile')),
                ('bio', models.CharField(max_length=200)),
                ('type_of_service', models.CharField(max_length=100)),
            ],
        ),
    ]
