# Generated by Django 5.1 on 2024-08-26 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0008_homeownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeownerprofile',
            name='homeowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arborfindr.homeowner'),
            preserve_default=False,
        ),
    ]
