# Generated by Django 5.1 on 2024-08-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0009_homeownerprofile_homeowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeownerprofile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
