# Generated by Django 5.1 on 2024-08-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arborfindr', '0010_alter_homeownerprofile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeownerprofile',
            name='type_of_service',
        ),
    ]
